### ISSUE TITLE
Is it possible to add the ability to buy a container?

### ISSUE THREAD

**Issue by webbfam** [nombersDev/casemove#133] opened 2023-07-02 10:40 UTC
Is it possible to add the ability to buy a container?

**Comment by TheMuchi** [comment] 2023-07-03 10:48
Duplicate of #58

**Comment by nombersDev** [comment] 2023-07-12 05:09
Thanks for the tag @TheMuchi

**Closed by nombersDev** 2023-07-12 05:09 UTC

**Comment by lmiol** [comment] 2023-07-17 19:48
https://partner.steamgames.com/doc/webapi_overview#1
Steam web-api not restrict to use in game purchase but vice versa, they say it's allowed.
![image](https://github.com/nombersDev/casemove/assets/264879/a433fd3b-a79e-4c37-83e4-3bfe25308cf4)
So it is possible =)
